### PR TITLE
add margin for Distance dimension text (solves Bug 145) - comments addressed

### PR DESCRIPTION
**Pull request by exegetor**
WIP.   Distance constraint looks OK.  Angle and Diameter not implemented yet.

https://user-images.githubusercontent.com/10360161/173745629-c30901cc-6c7c-482a-b42a-945c8136047c.mp4

### CODE REVIEW

**Comment by BaoNTGH** [comment]
Looks cool, I know it's not ready for review yet but wonder if the text should be rotated to parallel with dimension as well. Seeing other CADs doing that and I feel it's cleaner (not certainly we must do it but just something to call out)

**Comment by hlorus** [comment]
> Looks cool, I know it's not ready for review yet but wonder if the text should be rotated to parallel with dimension as well. Seeing other CADs doing that and I feel it's cleaner (not certainly we must do it but just something to call out)

There's actually a nice discussion about this already, see: https://github.com/hlorus/CAD_Sketcher/discussions/159

**Comment by exegetor** [comment]
Ok, all done.  The Diameter text now "avoids" landing on the center-point. which is a great side-effect!

**Comment by hlorus** [comment]
The margin for the diameter gizmo looks quite big when pulling it outside the circle, see:
image

Also i'm not sure if the margin has to be scaled, would probably work with a static value as well but no strong opinion on that.

**Comment by hlorus** [comment]
It looks like the branch changes some other things as well:
- Always place the text on the outside
- Size helpline overshoot by arrow scale

IMO these changes are good, just wanted to note to keep the overview.

**Comment by exegetor** [comment]
Removing the change to the helplines just so I can bundle it with another helpline upgrade.  (the outside Diameter, opposite side, needs a length limit.
I also increased the margin for Angle.  It looked too tight.
The values can still overlap the lines, but it's kinda a balance.  A margin big enough to always prevent overlap can leave the value hanging off in the distance.  Mostly with Distance constraint.  Rotating the text would fix that, but I'm starting to sweat over CPU cycles, ya know?

**Comment by hlorus** [comment]
Alright, this looks like it's good to go!

**Comment by hlorus** [comment]
Unfortunatley i had to revert the 3d-space based margin part of this PR for now. This was leading to issues when working in small scales.

See the commit for further details:
9bafbba83c41e7e350f30301c5e988e03550a367

**Pull request merged**
