### PR TITLE
add dimension line width setting to prefs (issue 143)

### PR DESCRIPTION
**Pull request by exegetor**
In case you think this is "good enough".    Separate widths for the leader lines vs witness lines will require much more thinking

### CODE REVIEW

**Comment by hlorus** [comment]
It would be great if someone could check if this works on mac, then we can add this.

**Comment by TheMakerTales** [comment]
@hlorus @exegetor 
Just tested this on a mac and it does not work =/

**Comment by exegetor** [comment]
@TheMakerTales that's what we expected, unfortunately.
As this PR comes out of a user request, I'll spend a little time looking into how this could be made to work on Mac.
I'm not optimistic about that...
As an alternative, what about making it a Win/Linux feature only?  (Mac wouldn't even see the option in Prefs)

**Comment by hlorus** [comment]
> @TheMakerTales that's what we expected, unfortunately.
> As this PR comes out of a user request, I'll spend a little time looking into how this could be made to work on Mac.
> I'm not optimistic about that...
> As an alternative, what about making it a Win/Linux feature only?  (Mac wouldn't even see the option in Prefs)
> 

I wouldn't invest too much time into a solution that doesn't support all platforms...
Better try to draw lines with filled rectangles, then we can use an arbitrary thickness. Afaik the LINES_TRIS type of new_custom_shape is used to draw surfaces, see: https://docs.blender.org/api/current/bpy.types.Gizmo.html#bpy.types.Gizmo.new_custom_shape

**Pull request closed without merging**
