### PR TITLE
add Preferences.show_mesh (recolves discussion 113)  COMMENTS ADDRESSED

### PR DESCRIPTION
**Pull request by exegetor**
Not sure how often I'd want to edit a sketch and see its mesh, but... users have asked for it, it doesn't chew up the CPU, 
 its easy to implement, and I had a few spare hours

### CODE REVIEW

**Review by hlorus — COMMENTED** [review]
Lgtm, the name is a bit misleading as it also applies to curve objects. Maybe something like:
"use_hide_objects"
"auto_hide_objects"

**Comment by exegetor** [comment]
should be good now.   I'm partially back from a family emergency.  I say partially, because it will linger a bit.

**Comment by hlorus** [comment]
Great to see you're back, hope everything is ok. I will have a look at the updated PR tomorrow.

**Comment by hlorus** [comment]
Merged with minor adjustments

**Pull request merged**
